# neo4j-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: neo4j
spec:
  clusterIP: None
  selector:
    app: neo4j
  ports:
    - name: bolt
      port: 7687
    - name: http
      port: 7474
    - name: https
      port: 7473
    - name: cluster
      port: 5000
    - name: tx
      port: 6000
    - name: raft
      port: 7000
